//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLChitieu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public TaiKhoan()
        {
            this.ChiRas = new HashSet<ChiRa>();
            this.ThuVaos = new HashSet<ThuVao>();
        }
    
        public string taiKhoan1 { get; set; }
        public string matKhau { get; set; }
    
        public virtual ICollection<ChiRa> ChiRas { get; set; }
        public virtual ICollection<ThuVao> ThuVaos { get; set; }
    }
}
